version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "8082:80"
    depends_on:
      - auth-service
      - blog-service
      - blog-comments-service
      # Add other services if the Angular app depends on them
    environment:
      AUTH_API_URL: "http://localhost:3000/"
      BLOG_SERVICE_API_URL: "http://localhost:8080/"
      COMMENTS_SERVICE_URL: "http://localhost:5000/"

  auth-service:
    build: C:\Users\sthot\OneDrive\Documents\AuthMicroService
    ports:
      - "3000:3000" # Adjust if your auth service runs on a different port
    env_file:
      - C:\Users\sthot\OneDrive\Documents\AuthMicroService\.env
      # Add other environment variables your auth service requires

  blog-service:
    build: C:\Users\sthot\OneDrive\Documents\BlogPostMicroService
    ports:
      - "8080:8080"
    env_file:
      - C:\Users\sthot\OneDrive\Documents\BlogPostMicroService\.env

  blog-comments-service:
    build: C:\Users\sthot\OneDrive\Documents\BlogCommentsMicroService
    ports:
      - "5000:5000"
    env_file:
      - C:\Users\sthot\OneDrive\Documents\BlogCommentsMicroService\.env

    